# Generated by Django 4.1.5 on 2023-02-21 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("planeacion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Confiabilidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor_tensiones",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Valor Tensiones"
                    ),
                ),
                (
                    "valor_corrientes",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Valor Corrientes"
                    ),
                ),
                (
                    "sincro_fecha",
                    models.BooleanField(verbose_name="Sincronizacion Fecha y Hora"),
                ),
                (
                    "validacion_canales",
                    models.BooleanField(verbose_name="Validacion Canales"),
                ),
                (
                    "cargue_fasorial",
                    models.FileField(upload_to="fasorial", verbose_name="Fasorial"),
                ),
                (
                    "orden_trabajo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="planeacion.planeacion",
                    ),
                ),
            ],
        ),
    ]
