# Generated by Django 4.1.5 on 2023-02-24 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planeacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hacer',
            options={'verbose_name': 'Hacer', 'verbose_name_plural': 'Modulo Hacer'},
        ),
    ]
