# Generated by Django 4.1.5 on 2023-01-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planeacion',
            name='estado',
            field=models.CharField(max_length=20),
        ),
    ]
