# Generated by Django 4.1.5 on 2023-02-03 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planeacion", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="planeacion", name="id_cuenta",),
        migrations.RemoveField(model_name="planeacion", name="nombre_cuenta",),
    ]
