# Generated by Django 4.1.5 on 2023-03-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confiabilidad',
            name='sincro_fecha',
            field=models.CharField(max_length=25, verbose_name='Sincronizacion Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='confiabilidad',
            name='validacion_canales',
            field=models.CharField(max_length=25, verbose_name='Validacion Canales'),
        ),
        migrations.AlterField(
            model_name='planeacion',
            name='estado',
            field=models.CharField(max_length=40),
        ),
    ]
