# Generated by Django 4.1.5 on 2023-02-24 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planeacion', '0002_alter_hacer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backlog',
            options={'verbose_name': 'Backlog', 'verbose_name_plural': 'Backlogs'},
        ),
        migrations.AlterModelOptions(
            name='evaluacion',
            options={'verbose_name': 'Evaluacion', 'verbose_name_plural': 'Modulo Evaluacion'},
        ),
        migrations.AlterModelOptions(
            name='planeacion',
            options={'verbose_name': 'Planeacion', 'verbose_name_plural': 'Modulo Planeacion'},
        ),
    ]
