# Generated by Django 4.1.5 on 2023-01-31 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planeacion", "0002_alter_planeacion_estado"),
    ]

    operations = [
        migrations.CreateModel(
            name="Backlog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "fuente",
                    models.CharField(max_length=50, verbose_name="Quien reporta"),
                ),
                (
                    "reporte",
                    models.CharField(max_length=250, verbose_name="Que reporta"),
                ),
                (
                    "id_punto_servicio",
                    models.CharField(max_length=15, verbose_name="ID Punto Servicio"),
                ),
                (
                    "ejecucion",
                    models.CharField(
                        max_length=200, verbose_name="Quien ejecuta la actividad"
                    ),
                ),
                (
                    "estado",
                    models.CharField(max_length=50, verbose_name="Estado Alerta"),
                ),
                (
                    "responsable",
                    models.CharField(max_length=200, verbose_name="Quien Resuelve"),
                ),
            ],
            options={"verbose_name": "Backlog", "verbose_name_plural": "Backlog",},
        ),
    ]
