# Generated by Django 4.1.5 on 2023-02-27 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planeacion', '0003_alter_backlog_options_alter_evaluacion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confiabilidad',
            options={'verbose_name': 'Confiabilidad', 'verbose_name_plural': 'Modulo Confiabilidad'},
        ),
    ]
