# Generated by Django 4.1.5 on 2023-02-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeacion', '0003_backlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='backlog',
            name='contrata',
            field=models.CharField(default=1, max_length=200, verbose_name='Contratista'),
            preserve_default=False,
        ),
    ]
